#! /bin/bash
####################################################################################
#	                   ___           ___         ___           ___		   #
#	     _____         /  /\         /  /\       /__/\         /__/\	   #
#	    /  /::\       /  /:/_       /  /::\     _\_ \:\       |  |::\	   #
#	   /  /:/\:\     /  /:/ /\     /  /:/\:\   /__/\ \:\      |  |:|:\  	   #
#	  /  /:/~/::\   /  /:/ /::\   /  /:/~/:/  _\_ \:\ \:\   __|__|:|\:\	   #
#	 /__/:/ /:/\:| /__/:/ /:/\:\ /__/:/ /:/  /__/\ \:\ \:\ /__/::::| \:\ 	   #
#	 \  \:\/:/~/:/ \  \:\/:/~/:/ \  \:\/:/   \  \:\ \:\/:/ \  \:\~~\__\/ 	   #
#	  \  \::/ /:/   \  \::/ /:/   \  \::/     \  \:\ \::/   \  \:\		   #
#	   \  \:\/:/     \__\/ /:/     \  \:\      \  \:\/:/     \  \:\	   #
#	    \  \::/        /__/:/       \  \:\      \  \::/       \  \:\	   #
#     	     \__\/         \__\/         \__\/       \__\/         \/		   #							   #
####################################################################################

		#	Mi configuracion de bspwm
		#	CallmeDav



###################################################################
		#Aplicaciones que incian en segundo plano
###################################################################

#Mato los procesos antes de iniciar sesion
killall mpd mopidy dropbox conky compton
#Demonio de acceso rapido teclas
sxhkd &
#Compositor para transparencias
compton &
#Demonio para reproducir musica desde consola
mpd &
#Fijar Wallpaper
nitrogen --restore &
#Demonio para notificaciones
dunst &
#Cursor
xsetroot -cursor_name left_ptr &
#Dropbox
dropbox &
#KDE-connect
kdeconnect-cli --refresh &
###############################################################
			#Scripts de inicio
###############################################################

#Ajuste de brilo
$HOME/.config/bspwm/scripts/brillo.sh &
#Lanza Conky
$HOME/.conky/conky-startup.sh &
#Panel de polybar
$HOME/.config/polybar/launch.sh &
$HOME/.config/polybar/scripts/colors-dark.sh -cyan &


################################################################
		#Configuracion de BSPWM
################################################################

			#Workspaces

#Declaracion de areas de trabajo
bspc monitor -d Home Web Code Math Music Social Sistem

			#Color

#Color de la ventana normal
bspc config normal_border_color         	"#3c4146"
#Color de la ventana enfocada
bspc config focused_border_color     		"#2d9d91"

	#Separacion de ventanas y grosor del borde

Border=6
#Grosor del borde
bspc config border_width         		$Border
#Separacion de ventanas
bspc config window_gap           		$Border

			#Margenes laterales
lateral=8
for side in right left ; do
        bspc config ${side}_padding $lateral
done

		#Margenes Superiores e Inferiores
sup=40
for side in top bottom ; do
        bspc config ${side}_padding $sup
done


	#Enfocar ventana solo desplazandose
bspc config focus_follows_pointer 		true


#################################################################
		#Reglas de las ventanas
#################################################################

		#Apicaciones Fullscreen

#bspc rule -a inkscape state=fullscreen
#bspc rule -a Spotify state=fullscreen
#bspc rule -a Vlc state=fullscreen
#bspc rule -a VirtualBox Manager state=fullscreen
#bspc rule -a VirtualBox Machine state=fullscreen



		#Floating applications

#bspc rule -a Arandr state=floating
#bspc rule -a feh state=floating
#bspc rule -a Galculator state=floating
#bspc rule -a Nitrogen state=floating
#bspc rule -a Oblogout state=floating

###################################################################
		#Aplicaciones por Workspaces
###################################################################

bspc rule -a URxvt border=off
	
			#Home
#bspc rule -a conky state=floating border=off

			#Web
bspc rule -a firefox desktop=\Web
bspc rule -a google-chrome desktop=\Web

			#Code
bspc rule -a Org.gnome.gedit desktop=\Code

			#Math
bspc rule -a Evince desktop=\Math
bspc rule -a Zathura state=tiled desktop=\Math
			#Music
bspc rule -a spotify-dev desktop=\Music
bspc rule -a ncmpcpp desktop=\Music
			#Social
bspc rule -a TelegramDesktop desktop=\Social

			#Sistem
bspc rule -a Nitrogen desktop=\Sistem
bspc rule -a pavucontrol desktop=\Sistem
bspc rule -a nm-conection-editor desktop=\Sistem
